---
name: Test PyPI Release

on:
  workflow_dispatch:  # Manual trigger for testing
    inputs:
      test_pypi:
        description: 'Publish to TestPyPI'
        required: false
        default: false
        type: boolean

jobs:
  test-build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Validate package
        run: |
          # Check that the package can be built and contains expected files
          python -m twine check dist/*

          # List built artifacts
          echo "Built artifacts:"
          ls -la dist/

          # Verify wheel can be installed and imported (test locally)
          echo "Testing package installation..."
          pip install dist/*.whl
          python -c \
            "import failextract; print('FailExtract imported successfully')"

      - name: Test publish to TestPyPI (optional)
        if: ${{ inputs.test_pypi }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          echo "Checking if package already exists on TestPyPI..."
          curl -s "https://test.pypi.org/pypi/failextract/json" | jq '.releases | keys' || echo "Package not found (which is good for first upload)"
          
          echo "Uploading to TestPyPI with verbose output..."
          python -m twine upload --repository testpypi --verbose --skip-existing dist/*